---
- debug:
    msg: "Hello from your external use case!"

- name: Enable Monaco
  include_role:
    name: monaco-v2

- debug:
    msg: "{{ ingress_domain }}"       

- include_role:
    name: monaco-v2
    tasks_from: apply-monaco
    apply:
      environment:
        DT_API_TOKEN: "{{ dynatrace_api_token }}"
        DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3.rstrip('/') }}"
        DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
        DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
        DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"
        INGRESS_DOMAIN: "{{ ingress_domain }}"
  vars:
    monaco_projects_root: "/home/dt_training/repos/biz-analytics-hot/roles/my-use-case/files/monaco" 
    monaco_project: "" 
    monaco_manifest_path: "/home/dt_training/repos/biz-analytics-hot/roles/my-use-case/files/monaco/manifest.yml"
    monaco_environment:
      DT_API_TOKEN: "{{ dynatrace_api_token }}"
      DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3.rstrip('/') }}"
      DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
      DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
      DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"
      INGRESS_DOMAIN: "{{ ingress_domain }}"

- include_role:
    name: k3s

# - name: Install dt operator
#   include_role:
#     name: dt-operator

- include_role:
    name: app-easytrade    

- name: Install Biz Flow App
  ignore_errors: true
  include_role:
    name: dt-platform
    tasks_from: ensure-app
  vars:
    dt_app_id: "{{ item.dt_app_id }}"
    dt_environment_url_gen3: "{{ extra_vars.dt_environment_url_gen3 }}"
    dt_oauth_sso_endpoint: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    dt_oauth_client_id: "{{ extra_vars.dt_oauth_client_id }}"
    dt_oauth_client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
    dt_oauth_account_urn: "{{ extra_vars.dt_oauth_account_urn }}"
  loop:
    - dt_app_id: "dynatrace.biz.flow"
      dt_app_version: "1.20.3"

- include_role:
    name: mattermost

- include_role:
    name: dashboard    
