---
- debug:
    msg: "Hello from your external use case!"

# - name: Monaco - Deploy configuration
#   include_role:
#     name: monaco-v2
#     tasks_from: apply-monaco
#   vars:
#     monaco_manifest_path: "/home/dt_training/repos/biz-analytics-hot/roles/my-use-case/files/monaco/manifest.yml"
#     monaco_environment:
#       DT_TOKEN: "{{ dynatrace_api_token}}"
#       DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3 }}"
#       DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
#       DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
#       DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"
#       AWX_CONTROLLER_TOKEN: "{{ awx_controller_token }}"
#       AWX_URL: "{{ ingress_protocol }}://ansible.{{ ingress_domain }}/api/v2/"


# - block:
#     - name: Install Kubernetes
#       include_role:
#         name: k3s
#   become: true
    # become_user: "{{ namespace }}"

# - name: Install dt operator
#   include_role:
#     name: dt-operator

# - include_role:
#     name: app-easytrade    

- name: Install Biz Flow App
  ignore_errors: true
  include_role:
    name: dt-platform
    tasks_from: ensure-app
  vars:
    dt_app_id: "{{ item.dt_app_id }}"
    dt_environment_url_gen3: "{{ extra_vars.dt_environment_url_gen3 }}"
    dt_oauth_sso_endpoint: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    dt_oauth_client_id: "{{ extra_vars.dt_oauth_client_id }}"
    dt_oauth_client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
    dt_oauth_account_urn: "{{ extra_vars.dt_oauth_account_urn }}"
  loop:
    - dt_app_id: "dynatrace.biz.flow"
      dt_app_version: "1.20.3"
