configs:
  - id: http-dotnet
    config:
      name: http-dotnet
      template: oneagent-feature.json
      skip: false
      parameters:
        featureKey: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment        
  - id: http-java
    config:
      name: http-java
      template: oneagent-feature.json
      skip: false
      parameters:
        featureKey: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment
  - id: statuscreated
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:created"
      template: statuscreated.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment
  - id: statusdelivered
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:delivered"
      template: statusdelivered.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment
  - id: statuserror
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:error"
      template: statuserror.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment
  - id: statusshipped
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders/\\{id\\}/status:shipped"
      template: statusshipped.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment
  - id: v1Orders
    config:
      name: "EasyTrade \\[credit\\-card\\-order\\-service | Java\\] \\- POST /v1/orders"
      template: v1Orders.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment
  - id: perform-hot-h02-workflow
    config:
      name: Perform HOT BizAnalytics - H02
      template: perform-hot-h02-workflow.json
      skip: false
      parameters:
        configCode:
          type: file
          path: retail-config.ts
        historicalDataCode:
          type: file
          path: historical-data.ts
        generateDataCode:
          type: file
          path: generate-new.ts
        processTemporaryCode:
          type: file
          path: process-temporary.ts        
