configs:
  - id: http-dotnet
    config:
      name: http-dotnet
      template: oneagent-feature.json
      skip: false
      parameters:
        featureKey: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment
        
  - id: http-java
    config:
      name: http-java
      template: oneagent-feature.json
      skip: false
      parameters:
        featureKey: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment
