manifestVersion: 1.0

projects:
  - name: bizevent-sensors
    path: monaco-configs/bizevent-sensors
    type: grouping

environmentGroups:
  - name: playground
    environments:
      - name: playground
        url:
          type: environment
          name: DT_PLATFORM_TENANT_URL
        auth:
          token:
            type: environment
            name: DT_TOKEN
          oAuth:
            clientId:
              type: environment
              name: DT_OAUTH_CLIENT_ID
            clientSecret:
              type: environment
              name: DT_OAUTH_CLIENT_SECRET
